### ISSUE TITLE
ModelOptimizer custom loss

### ISSUE THREAD

**Issue by Finn-Sueberkrueb** [JuliaComputing/JuliaSimIssues#4]
The [tutorial](https://help.juliahub.com/jsmo/stable/tutorials/loss/) seems to be faulty regarding the keyword argument and the form of the loss function.

Which seems to work for me:
```
function custom_loss(solution, dataset)
    # Calculate loss
    return scalar
end

Experiment(data, sys; err = custom_loss) 
```

**Comment by sathvikbhagavan** [comment]
Which version of Model Optimizer are you using? It seems you are using an earlier version.

`loss_func` was introduced in v8 (which is the latest) in favour of `err` and docs are built using the same.

`loss_func` accepts 3 arguments as mentioned in the tutorial.  `err` accepts only two arguments.

**Comment by Finn-Sueberkrueb** [comment]
JuliaSimModelOptimizer v6.1.4. That's the problem. Thanks @sathvikbhagavan.


I have a parallel ticket open via JuliaHub support to see if I can get access to a newer version for local installation.
Sorry for two open issues. I was unsure which channel was being used by you. I will close this one.

**Comment by ranjanan** [comment]
Yep, you should be able to access the latest ModelOptimizer now @Finn-Sueberkrueb. Thanks for contacting us!
