### ISSUE TITLE
Reference cache in JuliaSimControl.MPC

### ISSUE THREAD

**Issue by bertrandkerres** [JuliaComputing/JuliaSimIssues#5]
The `GenericMPCProblem` type advances its reference trajectory cache currently like this:

```julia
copyto!(xr, 1, xr, nx+1, length(xr)-nx) # advance xr
```
i.e. it copies the matrix one time step forward, and leaves the last time step untouched. This essentially leads to constant reference trajectory after the initial cache is consumed.

One should be able to update the reference trajectory e.g. through the `ControllerInput` or `ObserverInput` arguments. E.g. something like this:

```julia
function MPC.step!(prob, observer_input, ...)
    # Steps as before
    # ...

    # Update reference trajectory
    prob.xr[:, end] .= observer_input.r[:, end]
   
    # Rest as before
end
```

I don't know if only the last time step on the horizon or also earlier ones, I guess it could be problematic for the optimizer warm start if large parts of the reference trajectory are suddenly changed.

**Comment by baggepinnen** [comment]
Hello and thanks for the issue. Yeah you are right, it would be good to push a new element onto the end of the trajectory when taking a `step!`.

**Comment by baggepinnen** [comment]
`MPC.advance!(prob)` should probably take a `::ControllerInput`` which is forwarded to `MPC.advance_xr!` which should add the `r` at the end.

One could possibly want to update the reference trajectory in multiple different ways
- Replace the whole trajectory, in this case, `controllerinput.r::Matrix`
- Push a new element to the end, in this case, `controllerinput.r::Vector`

> I guess it could be problematic for the optimizer warm start if large parts of the reference trajectory are suddenly changed.

Probably, but if you're using IPOPT, which as an interior-point solver, the difference might not be huge. IPOPT is not very good at warm starting, and will usually leave the optimal point from previous iteration and take a few steps into the interior of the domain before moving back and converging onto the new optimum at the boundary of the domain. If the optimization landscape is such that there are multiple bad minima, those might of course become problematic, but that's likely not hard to realize.

**Comment by bertrandkerres** [comment]
You're right, as a user I think it would definitely be good to have the option to replace the whole trajectory, else I'm always locked in for the entire MPC horizon.

I agree, logically I would expect the updated `r` as part of a `::ControllerInput`. I mentioned `::ObserverInput` since that is part of the arguments to `step!` already, but maybe one can use a keyword argument?

In my own case, I have a custom `step!` function anyway for the Kalman filters with external input (seems to work, thanks again! :) ), so I'm also using `::ControllerInput`.

**Comment by baggepinnen** [comment]
A new release supporting this will be out shortly, thanks for opening this issue!

**Comment by bertrandkerres** [comment]
Thanks for the fast response ☺️

**Comment by baggepinnen** [comment]
A new issue in MTK was encountered when running tests, so the release is unfortunately delayed waiting for a fix
- https://github.com/SciML/ModelingToolkit.jl/issues/3087

cc @AayushSabharwal

**Comment by bertrandkerres** [comment]
No problem, thanks for the info 👍

**Comment by baggepinnen** [comment]
The new release has been merged, I guess it'll take an hour or so before it becomes available through the registry
